# Generated by Django 3.0.3 on 2020-03-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200302_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscraber', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
